debug: false # ??? ?? ???.
management.endpoints.web.exposure.include: "*" # ?????? ?????? ??? ?? ??? ????.

logging:
  level:
    com.example.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa query??? ????? ? ? ?? (?? ? ? ??)

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/board
    url: jdbc:postgresql://localhost:5432/board
    username: dbwp
    password: 1234
  #    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true # ???? db ??? ????? ? (data.sql)
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: create # ???? ?? ddl ???? (??? ????)
#    open-in-view: false
    show-sql: true # ????
    properties: # hibernate? ???? ?? ????? ???? ?? ? ?? ????.
      hibernate.format_sql: true # jpa ??? ???? -> hibernate
      hibernate.default_batch_fetch_size: 100 # jpa?? ??? ??? ??, bulk? ???? ?? (n+1??? ???? ?? ? ??)
    h2.console.enabled: false
  sql.init.mode: always # ??? ???? ?? ?? ?
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---

#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none





